### ISSUE TITLE
Minor cosmetic errors in NeuroView proof copy as of 20210423 11am CDT

### ISSUE THREAD

**Issue by SWideman** [brainhackorg/brainhack_jupyter_book#71]
Six instances of "Figure xxxxx" color inconsistency (e.g., "Figures 1A and 1B" on Page 1, where "Figures 1" portion is in blue and "A and 1B" are in black)

This variation occurs on Pages 1, 3, 5, 6 (2 instances) and 7.  

All can be found by searching for the term "Figure", ignoring obvious cases where the problem does not appear.
![image](https://user-images.githubusercontent.com/83085297/115903109-d38fdd00-a428-11eb-80f5-a97756edb8bd.png)

**Comment by Remi-Gau** [comment]
I actually think that I am going to keep it as is: the reason is that if you have a whole hyperlink for `Figure1C` then it could imply that the hyperlink is to that subfigure where as it is only to the whole figure. This mix of color might seem weird but just reflects the fact that we can only hyperlink to only the global figure and not sub panels.

**Comment by SWideman** [comment]
Understood, thanks for the explanation.  It does look a little weird, but
your reasoning for accuracy makes sense.

I'd have probably colored it all blue and *still* linked to the whole
figure.  The reader can easily focus on the specific section they're
looking for without doing a 'visual stutter' when they see the coloring
difference on the hyperlink (like I did).

Just a preference, but you're in charge - keep up the great work!
